### ISSUE TITLE
Materials Library: "source" and "date" are properties of "price", not "quote"

### ISSUE THREAD

**Issue by kvanalls** [NREL/catcost-data-tools#2]
See attached screenshot
![Screen Shot 2021-05-18 at 2 43 56 PM](https://user-images.githubusercontent.com/51412369/118721047-97615980-b7e7-11eb-92cc-cacacc924cdd.png)

**Comment by acjoven** [comment]
Issue resolved & tested in [782dc5d](https://github.com/NREL/catcost-data-tools/commit/782dc5df4ecdaaabe935edbb9f926669db906862
