### ISSUE TITLE
Spent Cat Library: do not write "density_si"; instead write "density_unit": "lb/ft3"

### ISSUE THREAD

**Issue by kvanalls** [NREL/catcost-data-tools#3]
Conversion is done automatically in the web. Read only from the column that has density in lb/ft3 and write the density_unit as lb/ft3.

**Comment by kvanalls** [comment]
In the case that a user hasn't entered anything in the p (lb/ft3) column, read the p (kg/m3) column instead and then write density_unit as "kg/m3"

**Comment by acjoven** [comment]
Resolved in [8374d96](https://github.com/NREL/catcost-data-tools/commit/8374d9611891d7ff49da5fec61dd647fff060ffb)
